"""
day3_inspector.py

Consolidated runner for Day-3 XBRL inspection.  Runs all four diagnostic
scripts against the cached 10-K (0001144879-26-000048) and produces a
single report:

  notes/day3_inspection/day3_report.txt

The four inspections:
  1. inspect_namespaces  -- which namespaces are standard vs company
  2. inspect_calc        -- debt-related calculation arcs (table + tree)
  3. inspect_instance    -- actual fact values + context details
  4. compare_linkbases   -- calc vs presentation for one shared debt concept

Usage:
    python day3_inspector.py
"""

from __future__ import annotations

import sys
from pathlib import Path

from common import (
    InspectionError,
    PROJECT_ROOT,
    TARGET_CAL,
    TARGET_INSTANCE,
    TARGET_PRE,
    banner,
    ensure_notes_dir,
    format_exception,
)

# Make sibling modules importable when run from anywhere
sys.path.insert(0, str(Path(__file__).resolve().parent))

from compare_linkbases import compare_linkbases  # noqa: E402
from inspect_calc import inspect_calc  # noqa: E402
from inspect_instance import inspect_instance  # noqa: E402
from inspect_namespaces import inspect_namespaces  # noqa: E402


def run_all(*, echo: bool = True) -> str:
    """Run all four inspections and return the consolidated report text."""
    checks = [
        ("NAMESPACES", lambda: inspect_namespaces(TARGET_INSTANCE, echo=False)),
        ("CALCULATION ARCS", lambda: inspect_calc(TARGET_CAL, echo=False)),
        ("INSTANCE FACTS", lambda: inspect_instance(TARGET_INSTANCE, echo=False)),
        ("CALC VS PRESENTATION", lambda: compare_linkbases(TARGET_CAL, TARGET_PRE, echo=False)),
    ]

    sections = []
    for title, fn in checks:
        try:
            body = fn()
        except InspectionError as exc:
            body = format_exception(exc)
        sections.append((title, body))

    parts: list[str] = []
    parts.append(
        banner(
            "DAY 3 -- MANUAL XBRL INSPECTION REPORT\n"
            f"  Filing: {TARGET_INSTANCE.parent.name} (10-K)\n"
            f"  Generated by: day3_inspector.py\n"
            f"  Use this to fill in notes/day3_manual_trace.md"
        )
    )

    for title, body in sections:
        parts.append(banner(f"INSPECTION: {title}", char="-"))
        parts.append(body.strip())
        parts.append("")

    report = "\n".join(parts)
    out_dir = ensure_notes_dir()
    out_path = out_dir / "day3_report.txt"
    out_path.write_text(report, encoding="utf-8")
    if echo:
        print(report)
        print(f"\nConsolidated report written to: {out_path}")
    return report


def main(argv: list[str] | None = None) -> int:
    run_all()
    return 0


if __name__ == "__main__":
    sys.exit(main())
