"""Runs diagnostic XBRL inspections and generates a consolidated report."""

import sys
from pathlib import Path

from common import (
    PROJECT_ROOT,
    TARGET_CAL,
    TARGET_INSTANCE,
    TARGET_PRE,
    InspectionError,
    banner,
    ensure_notes_dir,
    format_exception,
)
from compare_linkbases import compare_linkbases
from inspect_calc import inspect_calc
from inspect_instance import inspect_instance
from inspect_namespaces import inspect_namespaces


def run_all(*, echo: bool = True) -> str:
    """Run all four inspections and return the consolidated report text."""
    checks = [
        ("NAMESPACES", lambda: inspect_namespaces(TARGET_INSTANCE, echo=False)),
        ("CALCULATION ARCS", lambda: inspect_calc(TARGET_CAL, echo=False)),
        ("INSTANCE FACTS", lambda: inspect_instance(TARGET_INSTANCE, echo=False)),
        ("CALC VS PRESENTATION", lambda: compare_linkbases(TARGET_CAL, TARGET_PRE, echo=False)),
    ]

    sections = []
    for title, fn in checks:
        try:
            body = fn()
        except InspectionError as exc:
            body = format_exception(exc)
        sections.append((title, body))

    parts: list[str] = []
    parts.append(
        banner(
            "XBRL FILING INSPECTION REPORT\n"
            f"  Filing: {TARGET_INSTANCE.parent.name} (10-K)\n"
            f"  Generated by: inspect_all.py"
        )
    )

    for title, body in sections:
        parts.append(banner(f"INSPECTION: {title}", char="-"))
        parts.append(body.strip())
        parts.append("")

    report = "\n".join(parts)
    out_dir = ensure_notes_dir()
    out_path = out_dir / "xbrl_inspection_report.txt"
    out_path.write_text(report, encoding="utf-8")
    if echo:
        print(report)
        print(f"\nConsolidated report written to: {out_path}")
    return report


def main(argv: list[str] | None = None) -> int:
    run_all()
    return 0


if __name__ == "__main__":
    sys.exit(main())
